### ISSUE TITLE
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: http://download.thinkbroadband.com/100MB.zip

### ISSUE THREAD

**Issue by demostans** [takipi/aws-s3-speed#6]
I'm trying to run the application but it fails:

java -jar aws-s3-speed-0.0.5-SNAPSHOT-jar-with-dependencies.jar RUN **KEY** **SECRET** AWSS3speedTest 14052015 12 HUGE SDK
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: http://download.thinkbroadband.com/100MB.zip
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.net.URL.openStream(Unknown Source)
        at com.takipi.tests.speedtest.data.DataBytes.get100MBData(DataBytes.java:59)
        at com.takipi.tests.speedtest.data.DataBytes.getData(DataBytes.java:28)
        at com.takipi.tests.speedtest.Main.main(Main.java:41)

Downloading the file from my browser works fine.

Any ideas why it fails?

**Comment by sumwun1** [comment]
This might work. https://stackoverflow.com/questions/30092798/java-io-ioexception-server-returned-http-response-code-403-for-url
